name: contacts_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  audioplayers: ^1.0.1
  alphabet_scroll_view: ^0.3.1
  app_settings: ^4.1.8
  flutter_phone_direct_caller: ^2.1.1
  email_validator: ^2.1.17
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  flutter_sms: ^2.3.3
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/my_audio.mp3